### PR TITLE
Upgrade activesupport to v6.0.x; remove Ruby 2.4, add Ruby 2.7 to CI

### PR DESCRIPTION
**Pull request by dchandekstark**

### CODE REVIEW

**Comment by dchandekstark** [comment]
Looks like we need to replace `normalize` with `unicode_normalize` for activesupport 6.1+.

**Comment by adjam** [comment]
@dchandekstark have you tried this on Ruby 3.0 or 3.1?

If not, let me know and I can try building it with those versions.

**Comment by adjam** [comment]
`~> 6.0.0` restricts you to `activesupport` 6.0.* -- I would suggest `> 6.0` at this point to allow compatibility with Rails/ActiveSupport 6.1 and 7.x

**Comment by dchandekstark** [comment]
@adjam I have not tried Ruby 3.x.

**Comment by dchandekstark** [comment]
@adjam Regarding the ActiveSupport version, compatibility with v6.1 will require further changes.  With Ruby 2.7 and AS 6.1 I get 411 test failures.

**Pull request closed without merging**
