### PR TITLE
Miscellaneous shared and UNC-specific work

### PR DESCRIPTION
**Pull request by kspurgin**
DRAFT RELEASE: https://github.com/trln/marc-to-argot/releases/edit/untagged-77d63fc4c19311851e25

*SHARED*
* 245$h of [serial] or [printed music] no longer blocks assignment of physical_media = Print (TDU-44, TDU-56)
* physical_media values for microform/film/fiche/opaque now look at FormItem in 006/008 and 245$h in addition to 007 (TDU-44)
* Changed handling of 69X fields. These are, by definition, *local* fields, and were being handled in the shared config. UNC needed to change how some 69X were treated. This was only a change to what MARC fields should be mapped to what fields, not a change to the data transformation logic (how to create headings, facet values, etc). My solution was to set up mappings of 69X fields in each institution's marc_specs.yml - the 69xs are specified there under the Argot field name, with _local or _local_concatenated added to the end of the field name (to achieve different behavior in facet fields). I added code to the shared subject_genre macro to append these fields to the general spec used by each method in that macro. This way UNC can map 695 as a genre field and anyone else can map it as a subject field, and no one has to override the entire subject/genre macro. Nor do we have to specify out all the very complicated field mappings for subject/genre fields separately in every institution's marc_specs.

*UNC*
* continue working on indexing finding aid content in associated bib records
* handle offsite stored materials consistently in location facet (all are now scoped to Library Service Center) (TDU-55)
* set up location facet hierarchy for llhd
* remove alpha suffixes from OCLC 035 values (TDU-39)
* write EAD ID to misc_id field
* treat item 096s as NLM call numbers
* populate Technology and accessories resource_type facet values (TD-909)

(Something with the way our EAD XML files get served up seems to not play well with how Travis runs the tests. I've removed the test for actually getting an EAD file because it was often failing when run by Travis, though it always seems to pass in other relevant contexts.)

### CODE REVIEW

**Comment by kspurgin** [comment]
@corylown when you have some time, can you look at what I've done here with the 69X local subject/genre fields. I suspect this is the main thing that might be contentious in this PR.

**Comment by corylown** [comment]
@kspurgin I think the general approach to dealing with the shared/local specs for subject/genre is fine. Do you mind if I make the following modification (in each method) and push the change up?

```
            shared_spec = '600abcdfghjklmnopqrstux:'\
                          '610abcdfghklmnoprstux:'\
                          '611acdefghklnpqstux:'\
                          '630adfghklmnoprstx:'\
                          '647acdgx:'\
                          '648x:'\
                          '650abcdgx:'\
                          '651x:653|*0|a:653|*1|a:653|*2|a:'\
                          '653|*3|a:'\
                          '653|*4|a:'\
                          '656ax:'\
                          '657ax'
            local_spec = settings['specs'][:subject_topical_local]
            spec = [shared_spec, local_spec].join(':')
```

**Comment by kspurgin** [comment]
@corylown that's fine! Thanks!

**Comment by kspurgin** [comment]
@corylown I think that will make this at a good stopping point for merging, if you feel comfortable with that. I'll go update the draft release now.

**Comment by corylown** [comment]
@kspurgin sounds good

**Pull request merged**
